#![allow(dead_code)]
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SoftwareEntry {
    pub id: String,
    pub name: String,
    pub tagline: String,
    pub description: String,
    pub category: String,
    pub homepage: String,
    pub license: String,
    pub tags: Vec<String>,
    pub install: Vec<InstallOption>,
    pub featured: bool,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct InstallOption {
    pub method: String,
    pub command: String,
    pub notes: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Category {
    pub id: String,
    pub name: String,
    pub description: String,
    pub icon: String,
}

pub fn get_categories() -> Vec<Category> {
    vec![
        Category {
            id: "browsers".into(),
            name: "Browsers".into(),
            description: "Web browsers for navigating the internet".into(),
            icon: "Globe".into(),
        },
        Category {
            id: "communications".into(),
            name: "Communications".into(),
            description: "Chat, email, and communication tools".into(),
            icon: "MessageSquare".into(),
        },
        Category {
            id: "development".into(),
            name: "Development".into(),
            description: "Code editors, IDEs, and developer tooling".into(),
            icon: "Code2".into(),
        },
        Category {
            id: "documents".into(),
            name: "Documents".into(),
            description: "Office suites, note-taking, and PDF tools".into(),
            icon: "FileText".into(),
        },
        Category {
            id: "games".into(),
            name: "Games".into(),
            description: "Gaming clients, emulators, and game managers".into(),
            icon: "Gamepad2".into(),
        },
        Category {
            id: "multimedia".into(),
            name: "Multimedia".into(),
            description: "Audio, video, and media playback tools".into(),
            icon: "Play".into(),
        },
        Category {
            id: "self-hosted".into(),
            name: "Self-Hosted".into(),
            description: "Self-hosted services and server applications".into(),
            icon: "Server".into(),
        },
        Category {
            id: "utilities".into(),
            name: "Utilities".into(),
            description: "Everyday utility apps and system helpers".into(),
            icon: "Wrench".into(),
        },
        Category {
            id: "terminal".into(),
            name: "Terminal".into(),
            description: "Terminal emulators and shell tools".into(),
            icon: "Terminal".into(),
        },
        Category {
            id: "system".into(),
            name: "System".into(),
            description: "System management, monitors, and kernel tools".into(),
            icon: "Settings2".into(),
        },
        Category {
            id: "security".into(),
            name: "Security".into(),
            description: "Privacy, encryption, and password managers".into(),
            icon: "ShieldCheck".into(),
        },
        Category {
            id: "virtualization".into(),
            name: "Virtualization".into(),
            description: "VMs, containers, and sandboxing".into(),
            icon: "Box".into(),
        },
        Category {
            id: "education".into(),
            name: "Education".into(),
            description: "Learning, science, and reference applications".into(),
            icon: "GraduationCap".into(),
        },
        Category {
            id: "graphics".into(),
            name: "Graphics".into(),
            description: "Image editing, 3D modelling, and design tools".into(),
            icon: "Palette".into(),
        },
    ]
}

pub fn get_software_catalogue() -> Vec<SoftwareEntry> {
    vec![
        // ==================== BROWSERS ====================
        SoftwareEntry {
            id: "firefox".into(),
            name: "Firefox".into(),
            tagline: "Fast, private, and secure web browser".into(),
            description: "Mozilla Firefox is a free and open-source web browser. Known for its strong privacy stance, extensive customization options, and support for open web standards.".into(),
            category: "browsers".into(),
            homepage: "https://www.mozilla.org/firefox/".into(),
            license: "MPL-2.0".into(),
            tags: vec!["browser".into(), "web".into(), "privacy".into(), "gecko".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S firefox".into(), notes: None },
                InstallOption { method: "paru".into(), command: "paru -S firefox".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub org.mozilla.firefox".into(), notes: None },
                InstallOption { method: "apt".into(), command: "sudo apt install firefox".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "zen-browser".into(),
            name: "Zen Browser".into(),
            tagline: "Firefox-based browser focused on privacy and beauty".into(),
            description: "Zen Browser is a modern Firefox fork featuring split-view, compact sidebar tabs, workspaces, and sleek styling designed for power users.".into(),
            category: "browsers".into(),
            homepage: "https://zen-browser.app/".into(),
            license: "MPL-2.0".into(),
            tags: vec!["browser".into(), "privacy".into(), "firefox".into(), "workspaces".into()],
            featured: true,
            install: vec![
                InstallOption { method: "aur".into(), command: "paru -S zen-browser-bin".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub app.zen_browser.zen".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "brave".into(),
            name: "Brave Browser".into(),
            tagline: "Privacy-focused browser with built-in ad blocking".into(),
            description: "Brave blocks trackers and ads automatically while providing Chromium engine speed and full WebStore extension compatibility.".into(),
            category: "browsers".into(),
            homepage: "https://brave.com/".into(),
            license: "MPL-2.0".into(),
            tags: vec!["browser".into(), "privacy".into(), "adblock".into(), "chromium".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S brave-bin".into(), notes: None },
                InstallOption { method: "aur".into(), command: "paru -S brave-bin".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub com.brave.Browser".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "chromium".into(),
            name: "Chromium".into(),
            tagline: "Open-source foundation behind Google Chrome".into(),
            description: "Chromium provides a clean, fast, and open-source Blink engine experience without Google proprietary telemetry.".into(),
            category: "browsers".into(),
            homepage: "https://www.chromium.org/".into(),
            license: "BSD-3-Clause".into(),
            tags: vec!["browser".into(), "web".into(), "blink".into()],
            featured: false,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S chromium".into(), notes: None },
                InstallOption { method: "apt".into(), command: "sudo apt install chromium-browser".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub org.chromium.Chromium".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "vivaldi".into(),
            name: "Vivaldi".into(),
            tagline: "Feature-rich customizable browser for power users".into(),
            description: "Vivaldi offers deep customization, tab stacking, mouse gestures, built-in notes, and email client for productivity enthusiasts.".into(),
            category: "browsers".into(),
            homepage: "https://vivaldi.com/".into(),
            license: "Proprietary".into(),
            tags: vec!["browser".into(), "customizable".into(), "tabs".into()],
            featured: false,
            install: vec![
                InstallOption { method: "aur".into(), command: "paru -S vivaldi".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub com.vivaldi.Vivaldi".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "tor-browser".into(),
            name: "Tor Browser".into(),
            tagline: "Anonymous and onion-routed web browsing".into(),
            description: "Tor Browser routes traffic across the distributed Tor network to protect privacy against surveillance and fingerprinting.".into(),
            category: "browsers".into(),
            homepage: "https://www.torproject.org/".into(),
            license: "BSD-3-Clause".into(),
            tags: vec!["browser".into(), "privacy".into(), "tor".into(), "anonymity".into()],
            featured: false,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S torbrowser-launcher".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub org.torproject.torbrowser-launcher".into(), notes: None },
            ],
        },

        // ==================== DEVELOPMENT ====================
        SoftwareEntry {
            id: "visual-studio-code".into(),
            name: "Visual Studio Code".into(),
            tagline: "Extensible code editor with massive ecosystem".into(),
            description: "VS Code is Microsoft's open-core source code editor with built-in Git, debugging, intelligent code completion (IntelliSense), and rich extension marketplace.".into(),
            category: "development".into(),
            homepage: "https://code.visualstudio.com/".into(),
            license: "Proprietary".into(),
            tags: vec!["editor".into(), "ide".into(), "typescript".into(), "debugging".into()],
            featured: true,
            install: vec![
                InstallOption { method: "aur".into(), command: "paru -S visual-studio-code-bin".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub com.visualstudio.code".into(), notes: None },
                InstallOption { method: "snap".into(), command: "sudo snap install --classic code".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "vscodium".into(),
            name: "VSCodium".into(),
            tagline: "Free/libre community distribution of VS Code".into(),
            description: "VSCodium is a community-driven, 100% open-source binary build of Microsoft's VS Code repository with telemetry and proprietary tracking completely removed.".into(),
            category: "development".into(),
            homepage: "https://vscodium.com/".into(),
            license: "MIT".into(),
            tags: vec!["editor".into(), "privacy".into(), "opensource".into()],
            featured: true,
            install: vec![
                InstallOption { method: "aur".into(), command: "paru -S vscodium-bin".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub com.vscodium.codium".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "neovim".into(),
            name: "Neovim".into(),
            tagline: "Hyperextensible Vim-based text editor".into(),
            description: "Neovim refactors Vim for extensible Lua scripting, modern LSP client integration, asynchronous IO, and beautiful terminal and GUI experiences.".into(),
            category: "development".into(),
            homepage: "https://neovim.io/".into(),
            license: "Apache-2.0".into(),
            tags: vec!["editor".into(), "vim".into(), "lua".into(), "lsp".into(), "terminal".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S neovim".into(), notes: None },
                InstallOption { method: "paru".into(), command: "paru -S neovim".into(), notes: None },
                InstallOption { method: "apt".into(), command: "sudo apt install neovim".into(), notes: None },
                InstallOption { method: "brew".into(), command: "brew install neovim".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "helix".into(),
            name: "Helix".into(),
            tagline: "Post-modern modal text editor in Rust".into(),
            description: "Helix is a modal text editor with Kakoune-style multiple selections, built-in Tree-sitter syntax highlighting, and zero-config LSP support out of the box.".into(),
            category: "development".into(),
            homepage: "https://helix-editor.com/".into(),
            license: "MPL-2.0".into(),
            tags: vec!["editor".into(), "rust".into(), "modal".into(), "treesitter".into()],
            featured: false,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S helix".into(), notes: None },
                InstallOption { method: "paru".into(), command: "paru -S helix".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub com.helix_editor.Helix".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "zed".into(),
            name: "Zed".into(),
            tagline: "High-performance multiplayer code editor".into(),
            description: "Zed is a next-generation code editor written in Rust with GPU-accelerated rendering, real-time collaboration, and instant startup times.".into(),
            category: "development".into(),
            homepage: "https://zed.dev/".into(),
            license: "GPL-3.0".into(),
            tags: vec!["editor".into(), "rust".into(), "fast".into(), "gpu".into()],
            featured: true,
            install: vec![
                InstallOption { method: "aur".into(), command: "paru -S zed-preview-bin".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub dev.zed.Zed".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "gitkraken".into(),
            name: "GitKraken".into(),
            tagline: "Visual Git GUI client and merge conflict resolver".into(),
            description: "GitKraken is a powerful visual Git GUI featuring interactive rebase, branch visualization, commit graph inspection, and workspace management.".into(),
            category: "development".into(),
            homepage: "https://www.gitkraken.com/".into(),
            license: "Freemium".into(),
            tags: vec!["git".into(), "gui".into(), "vcs".into()],
            featured: false,
            install: vec![
                InstallOption { method: "aur".into(), command: "paru -S gitkraken".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub com.axosoft.GitKraken".into(), notes: None },
            ],
        },

        // ==================== TERMINAL ====================
        SoftwareEntry {
            id: "alacritty".into(),
            name: "Alacritty".into(),
            tagline: "GPU-accelerated terminal emulator in Rust".into(),
            description: "Alacritty is a cross-platform, OpenGL-accelerated terminal emulator focusing on pure speed, simplicity, and rock-solid performance.".into(),
            category: "terminal".into(),
            homepage: "https://alacritty.org/".into(),
            license: "Apache-2.0".into(),
            tags: vec!["terminal".into(), "gpu".into(), "rust".into(), "fast".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S alacritty".into(), notes: None },
                InstallOption { method: "apt".into(), command: "sudo apt install alacritty".into(), notes: None },
                InstallOption { method: "paru".into(), command: "paru -S alacritty".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "kitty".into(),
            name: "Kitty".into(),
            tagline: "Feature-rich GPU terminal with graphics protocol".into(),
            description: "Kitty is a fast GPU-accelerated terminal emulator featuring tabs, splits, image display protocol, ligatures, and custom kitty extensions.".into(),
            category: "terminal".into(),
            homepage: "https://sw.kovidgoyal.net/kitty/".into(),
            license: "GPL-3.0".into(),
            tags: vec!["terminal".into(), "gpu".into(), "graphics".into(), "splits".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S kitty".into(), notes: None },
                InstallOption { method: "apt".into(), command: "sudo apt install kitty".into(), notes: None },
                InstallOption { method: "paru".into(), command: "paru -S kitty".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "wezterm".into(),
            name: "WezTerm".into(),
            tagline: "Multiplexer terminal emulator with Lua config".into(),
            description: "WezTerm is a GPU-accelerated terminal emulator and multiplexer configured via Lua, offering deep font rendering, tab bars, and SSH integration.".into(),
            category: "terminal".into(),
            homepage: "https://wezfurlong.org/wezterm/".into(),
            license: "MIT".into(),
            tags: vec!["terminal".into(), "lua".into(), "multiplexer".into(), "rust".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S wezterm".into(), notes: None },
                InstallOption { method: "aur".into(), command: "paru -S wezterm-git".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub org.wezfurlong.wezterm".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "ghostty".into(),
            name: "Ghostty".into(),
            tagline: "Fast, native, feature-rich terminal in Zig".into(),
            description: "Ghostty is a modern terminal emulator built in Zig and native platform UI (GTK on Linux), focusing on native performance, tabs, and aesthetics.".into(),
            category: "terminal".into(),
            homepage: "https://ghostty.org/".into(),
            license: "MIT".into(),
            tags: vec!["terminal".into(), "zig".into(), "native".into(), "gtk".into()],
            featured: true,
            install: vec![
                InstallOption { method: "aur".into(), command: "paru -S ghostty".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "tmux".into(),
            name: "tmux".into(),
            tagline: "Terminal multiplexer with persistent sessions".into(),
            description: "tmux allows switching easily between several programs in one terminal, detaching them and keeping them running in the background.".into(),
            category: "terminal".into(),
            homepage: "https://github.com/tmux/tmux".into(),
            license: "ISC".into(),
            tags: vec!["terminal".into(), "multiplexer".into(), "cli".into()],
            featured: false,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S tmux".into(), notes: None },
                InstallOption { method: "apt".into(), command: "sudo apt install tmux".into(), notes: None },
            ],
        },

        // ==================== COMMUNICATIONS ====================
        SoftwareEntry {
            id: "discord".into(),
            name: "Discord".into(),
            tagline: "Voice, video, and text communication platform".into(),
            description: "Discord is the all-in-one voice and text chat platform popular with gaming, developer communities, and friend groups.".into(),
            category: "communications".into(),
            homepage: "https://discord.com/".into(),
            license: "Proprietary".into(),
            tags: vec!["chat".into(), "voice".into(), "video".into(), "community".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S discord".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub com.discordapp.Discord".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "vesktop".into(),
            name: "Vesktop".into(),
            tagline: "Vencord-powered Discord desktop with Wayland screensharing".into(),
            description: "Vesktop is a lightweight Discord desktop client giving you Vencord plugin integration, crisp audio, and full Wayland screensharing with audio support.".into(),
            category: "communications".into(),
            homepage: "https://github.com/Vencord/Vesktop".into(),
            license: "GPL-3.0".into(),
            tags: vec!["chat".into(), "discord".into(), "wayland".into(), "vencord".into()],
            featured: true,
            install: vec![
                InstallOption { method: "aur".into(), command: "paru -S vesktop-bin".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub dev.vencord.Vesktop".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "telegram-desktop".into(),
            name: "Telegram Desktop".into(),
            tagline: "Fast and cloud-synced instant messaging client".into(),
            description: "Official desktop client for the Telegram messaging service, featuring instant synchronization, bot integrations, and channel broadcasts.".into(),
            category: "communications".into(),
            homepage: "https://desktop.telegram.org/".into(),
            license: "GPL-3.0".into(),
            tags: vec!["chat".into(), "messaging".into(), "telegram".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S telegram-desktop".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub org.telegram.desktop".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "signal-desktop".into(),
            name: "Signal Desktop".into(),
            tagline: "End-to-end encrypted private messaging".into(),
            description: "Signal is the industry standard for private, end-to-end encrypted messaging, voice, and video calling without advertising or trackers.".into(),
            category: "communications".into(),
            homepage: "https://signal.org/".into(),
            license: "AGPL-3.0".into(),
            tags: vec!["chat".into(), "privacy".into(), "encryption".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S signal-desktop".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub org.signal.Signal".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "thunderbird".into(),
            name: "Thunderbird".into(),
            tagline: "Free email, calendar, and contacts client".into(),
            description: "Mozilla Thunderbird is a fully featured email client supporting OpenPGP encryption, calendar scheduling, RSS feeds, and multiple IMAP/POP accounts.".into(),
            category: "communications".into(),
            homepage: "https://www.thunderbird.net/".into(),
            license: "MPL-2.0".into(),
            tags: vec!["email".into(), "calendar".into(), "openpgp".into()],
            featured: false,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S thunderbird".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub org.mozilla.Thunderbird".into(), notes: None },
            ],
        },

        // ==================== MULTIMEDIA ====================
        SoftwareEntry {
            id: "vlc".into(),
            name: "VLC Media Player".into(),
            tagline: "Universal media player that plays any format".into(),
            description: "VLC is a free and open-source cross-platform multimedia player that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and streaming protocols.".into(),
            category: "multimedia".into(),
            homepage: "https://www.videolan.org/vlc/".into(),
            license: "GPL-2.0".into(),
            tags: vec!["player".into(), "video".into(), "audio".into(), "codecs".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S vlc".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub org.videolan.VLC".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "mpv".into(),
            name: "mpv".into(),
            tagline: "Minimalist, scriptable command-line media player".into(),
            description: "mpv is a free, open-source, and versatile media player with powerful hardware video decoding, Lua scripting, and high-quality video output shaders.".into(),
            category: "multimedia".into(),
            homepage: "https://mpv.io/".into(),
            license: "GPL-2.0".into(),
            tags: vec!["player".into(), "minimalist".into(), "lua".into(), "gpu".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S mpv".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub io.mpv.Mpv".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "obs-studio".into(),
            name: "OBS Studio".into(),
            tagline: "Live streaming and video recording studio".into(),
            description: "OBS Studio is free and open-source software for video recording and live streaming, supporting PipeWire audio/video capture on Linux.".into(),
            category: "multimedia".into(),
            homepage: "https://obsproject.com/".into(),
            license: "GPL-2.0".into(),
            tags: vec!["streaming".into(), "recording".into(), "pipewire".into(), "video".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S obs-studio".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub com.obsproject.Studio".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "spotify".into(),
            name: "Spotify".into(),
            tagline: "Digital music, podcast, and audio streaming service".into(),
            description: "Spotify desktop application gives access to millions of songs, playlists, personalized recommendations, and high bitrate audio streaming.".into(),
            category: "multimedia".into(),
            homepage: "https://www.spotify.com/".into(),
            license: "Proprietary".into(),
            tags: vec!["music".into(), "streaming".into(), "podcasts".into()],
            featured: true,
            install: vec![
                InstallOption { method: "aur".into(), command: "paru -S spotify".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub com.spotify.Client".into(), notes: None },
            ],
        },

        // ==================== GAMES ====================
        SoftwareEntry {
            id: "steam".into(),
            name: "Steam".into(),
            tagline: "Ultimate digital gaming distribution platform".into(),
            description: "Steam on Linux provides seamless access to thousands of native and Windows games through Valve's Proton compatibility layer.".into(),
            category: "games".into(),
            homepage: "https://store.steampowered.com/".into(),
            license: "Proprietary".into(),
            tags: vec!["gaming".into(), "proton".into(), "store".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S steam".into(), notes: Some("Enable multilib repo first".into()) },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub com.valvesoftware.Steam".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "lutris".into(),
            name: "Lutris".into(),
            tagline: "Open gaming platform for GOG, Epic, and Wine".into(),
            description: "Lutris helps you install and manage games from GOG, Steam, Epic Games Store, emulators, and classic PC titles in one launcher.".into(),
            category: "games".into(),
            homepage: "https://lutris.net/".into(),
            license: "GPL-3.0".into(),
            tags: vec!["gaming".into(), "wine".into(), "emulators".into(), "launcher".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S lutris".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub net.lutris.Lutris".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "heroic-games-launcher".into(),
            name: "Heroic Games Launcher".into(),
            tagline: "Native GOG, Epic Games, and Amazon Prime launcher".into(),
            description: "Heroic is a clean, native gaming launcher for Epic Games, GOG, and Amazon Games using Wine, Proton, and DXVK.".into(),
            category: "games".into(),
            homepage: "https://heroicgameslauncher.com/".into(),
            license: "GPL-3.0".into(),
            tags: vec!["gaming".into(), "epic".into(), "gog".into(), "proton".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S heroic-games-launcher-bin".into(), notes: None },
                InstallOption { method: "aur".into(), command: "paru -S heroic-games-launcher-bin".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub com.heroicgameslauncher.hgl".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "protonup-qt".into(),
            name: "ProtonUp-Qt".into(),
            tagline: "Install and manage GE-Proton and Wine runners".into(),
            description: "ProtonUp-Qt makes it easy to install and update GE-Proton, Luxtorpeda, and custom Wine versions for Steam and Lutris.".into(),
            category: "games".into(),
            homepage: "https://davidotek.github.io/protonup-qt/".into(),
            license: "GPL-3.0".into(),
            tags: vec!["gaming".into(), "proton".into(), "wine".into(), "compatibility".into()],
            featured: false,
            install: vec![
                InstallOption { method: "aur".into(), command: "paru -S protonup-qt".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub net.davidotek.pupgui2".into(), notes: None },
            ],
        },

        // ==================== DOCUMENTS ====================
        SoftwareEntry {
            id: "obsidian".into(),
            name: "Obsidian".into(),
            tagline: "Knowledge base on local Markdown files".into(),
            description: "Obsidian is a powerful knowledge base and note-taking app that works on top of a local folder of plain Markdown files, with rich graph visualization.".into(),
            category: "documents".into(),
            homepage: "https://obsidian.md/".into(),
            license: "Proprietary".into(),
            tags: vec!["notes".into(), "markdown".into(), "knowledge".into(), "pkm".into()],
            featured: true,
            install: vec![
                InstallOption { method: "aur".into(), command: "paru -S obsidian".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub md.obsidian.Obsidian".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "libreoffice".into(),
            name: "LibreOffice".into(),
            tagline: "Comprehensive open-source office suite".into(),
            description: "LibreOffice is the full-featured, open-source personal productivity suite that includes Writer (word processing), Calc (spreadsheets), and Impress (presentations).".into(),
            category: "documents".into(),
            homepage: "https://www.libreoffice.org/".into(),
            license: "MPL-2.0".into(),
            tags: vec!["office".into(), "documents".into(), "spreadsheet".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S libreoffice-fresh".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub org.libreoffice.LibreOffice".into(), notes: None },
            ],
        },

        // ==================== GRAPHICS ====================
        SoftwareEntry {
            id: "gimp".into(),
            name: "GIMP".into(),
            tagline: "GNU Image Manipulation Program".into(),
            description: "GIMP is a cross-platform image editor used for photo retouching, image composition, and image authoring.".into(),
            category: "graphics".into(),
            homepage: "https://www.gimp.org/".into(),
            license: "GPL-3.0".into(),
            tags: vec!["photo".into(), "image".into(), "raster".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S gimp".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub org.gimp.GIMP".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "inkscape".into(),
            name: "Inkscape".into(),
            tagline: "Professional vector graphics editor (SVG)".into(),
            description: "Inkscape is a professional vector graphics editor for creating illustrations, icons, logos, diagrams, and complex vector art.".into(),
            category: "graphics".into(),
            homepage: "https://inkscape.org/".into(),
            license: "GPL-3.0".into(),
            tags: vec!["vector".into(), "svg".into(), "design".into(), "illustration".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S inkscape".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub org.inkscape.Inkscape".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "blender".into(),
            name: "Blender".into(),
            tagline: "Free and open-source 3D creation suite".into(),
            description: "Blender supports the entirety of the 3D pipeline—modeling, rigging, animation, simulation, rendering, compositing and motion tracking.".into(),
            category: "graphics".into(),
            homepage: "https://www.blender.org/".into(),
            license: "GPL-2.0".into(),
            tags: vec!["3d".into(), "modeling".into(), "rendering".into(), "animation".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S blender".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub org.blender.Blender".into(), notes: None },
            ],
        },

        // ==================== SYSTEM & UTILITIES ====================
        SoftwareEntry {
            id: "btop".into(),
            name: "btop".into(),
            tagline: "Resource monitor that shows usage and stats".into(),
            description: "btop is a modern, responsive TUI monitor for CPU, memory, disks, network, and processes with game-like visual graphs.".into(),
            category: "system".into(),
            homepage: "https://github.com/aristocratos/btop".into(),
            license: "Apache-2.0".into(),
            tags: vec!["monitor".into(), "tui".into(), "cpu".into(), "ram".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S btop".into(), notes: None },
                InstallOption { method: "apt".into(), command: "sudo apt install btop".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "fastfetch".into(),
            name: "fastfetch".into(),
            tagline: "Lightning-fast neofetch-like system info tool".into(),
            description: "Fastfetch is a neofetch-like tool for fetching system information and displaying it prettily, written in C for maximum speed.".into(),
            category: "system".into(),
            homepage: "https://github.com/fastfetch-cli/fastfetch".into(),
            license: "MIT".into(),
            tags: vec!["sysinfo".into(), "cli".into(), "c".into(), "speed".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S fastfetch".into(), notes: None },
                InstallOption { method: "apt".into(), command: "sudo apt install fastfetch".into(), notes: None },
            ],
        },

        // ==================== SECURITY ====================
        SoftwareEntry {
            id: "bitwarden".into(),
            name: "Bitwarden".into(),
            tagline: "Open-source password manager for all devices".into(),
            description: "Bitwarden is the easiest and safest way to store all of your logins and passwords while keeping them synced across all of your devices.".into(),
            category: "security".into(),
            homepage: "https://bitwarden.com/".into(),
            license: "GPL-3.0".into(),
            tags: vec!["password".into(), "security".into(), "vault".into(), "2fa".into()],
            featured: true,
            install: vec![
                InstallOption { method: "aur".into(), command: "paru -S bitwarden".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub com.bitwarden.desktop".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "keepassxc".into(),
            name: "KeePassXC".into(),
            tagline: "Offline, encrypted local password manager".into(),
            description: "KeePassXC stores passwords in an offline, heavily encrypted database (KDBX) without third-party cloud dependence.".into(),
            category: "security".into(),
            homepage: "https://keepassxc.org/".into(),
            license: "GPL-3.0".into(),
            tags: vec!["password".into(), "offline".into(), "encryption".into(), "security".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S keepassxc".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub org.keepassxc.KeePassXC".into(), notes: None },
            ],
        },

        // ==================== VIRTUALIZATION ====================
        SoftwareEntry {
            id: "docker".into(),
            name: "Docker".into(),
            tagline: "Containerization platform for developers".into(),
            description: "Docker enables developers to build, share, and run applications in isolated container environments with unified tooling.".into(),
            category: "virtualization".into(),
            homepage: "https://www.docker.com/".into(),
            license: "Apache-2.0".into(),
            tags: vec!["containers".into(), "docker".into(), "devops".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S docker docker-compose".into(), notes: None },
                InstallOption { method: "apt".into(), command: "sudo apt install docker.io".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "podman".into(),
            name: "Podman".into(),
            tagline: "Rootless and daemonless container engine".into(),
            description: "Podman is a daemonless, rootless container engine for developing, managing, and running OCI Containers on Linux systems.".into(),
            category: "virtualization".into(),
            homepage: "https://podman.io/".into(),
            license: "Apache-2.0".into(),
            tags: vec!["containers".into(), "rootless".into(), "daemonless".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S podman podman-compose".into(), notes: None },
                InstallOption { method: "apt".into(), command: "sudo apt install podman".into(), notes: None },
            ],
        },

        // ==================== UTILITIES ====================
        SoftwareEntry {
            id: "fzf".into(),
            name: "fzf".into(),
            tagline: "General-purpose command-line fuzzy finder".into(),
            description: "fzf is an interactive Unix filter for command-line that can be used with any list; files, command history, processes, hostnames, bookmarks, git commits, etc.".into(),
            category: "utilities".into(),
            homepage: "https://github.com/junegunn/fzf".into(),
            license: "MIT".into(),
            tags: vec!["fuzzy".into(), "cli".into(), "productivity".into(), "terminal".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S fzf".into(), notes: None },
                InstallOption { method: "apt".into(), command: "sudo apt install fzf".into(), notes: None },
                InstallOption { method: "brew".into(), command: "brew install fzf".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "ripgrep".into(),
            name: "ripgrep".into(),
            tagline: "Fast line-oriented search tool in Rust".into(),
            description: "ripgrep recursively searches directories for a regex pattern while respecting your gitignore rules by default, outperforming all legacy grep utilities.".into(),
            category: "utilities".into(),
            homepage: "https://github.com/BurntSushi/ripgrep".into(),
            license: "MIT".into(),
            tags: vec!["grep".into(), "search".into(), "fast".into(), "rust".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S ripgrep".into(), notes: None },
                InstallOption { method: "apt".into(), command: "sudo apt install ripgrep".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "bat".into(),
            name: "bat".into(),
            tagline: "A cat clone with syntax highlighting and Git integration".into(),
            description: "bat supports syntax highlighting for a large number of programming and markup languages, git modification markers, and automatic paging.".into(),
            category: "utilities".into(),
            homepage: "https://github.com/sharkdp/bat".into(),
            license: "Apache-2.0".into(),
            tags: vec!["cli".into(), "viewer".into(), "syntax".into(), "rust".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S bat".into(), notes: None },
                InstallOption { method: "apt".into(), command: "sudo apt install bat".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "flameshot".into(),
            name: "Flameshot".into(),
            tagline: "Powerful yet simple to use screenshot software".into(),
            description: "Flameshot is a feature-packed screenshot utility with built-in annotations, blur, arrows, pins, and direct imgur/cloud uploads.".into(),
            category: "utilities".into(),
            homepage: "https://flameshot.org/".into(),
            license: "GPL-3.0".into(),
            tags: vec!["screenshot".into(), "capture".into(), "annotation".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S flameshot".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub org.flameshot.Flameshot".into(), notes: None },
            ],
        },

        // ==================== SELF-HOSTED ====================
        SoftwareEntry {
            id: "nextcloud".into(),
            name: "Nextcloud".into(),
            tagline: "Self-hosted productivity platform for files, cal, and chat".into(),
            description: "Nextcloud puts you in control of your data, files, calendars, and communications on your own servers with enterprise-grade security.".into(),
            category: "self-hosted".into(),
            homepage: "https://nextcloud.com/".into(),
            license: "AGPL-3.0".into(),
            tags: vec!["cloud".into(), "storage".into(), "files".into(), "sync".into()],
            featured: true,
            install: vec![
                InstallOption { method: "aur".into(), command: "paru -S nextcloud".into(), notes: None },
                InstallOption { method: "snap".into(), command: "sudo snap install nextcloud".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "jellyfin".into(),
            name: "Jellyfin".into(),
            tagline: "The Free Software Media System".into(),
            description: "Jellyfin is a volunteer-built media solution that puts you in control of managing, streaming, and transcoding your movies, shows, and music collection.".into(),
            category: "self-hosted".into(),
            homepage: "https://jellyfin.org/".into(),
            license: "GPL-2.0".into(),
            tags: vec!["media".into(), "streaming".into(), "server".into(), "movies".into()],
            featured: true,
            install: vec![
                InstallOption { method: "aur".into(), command: "paru -S jellyfin-server jellyfin-web".into(), notes: None },
                InstallOption { method: "pacman".into(), command: "sudo pacman -S jellyfin-server jellyfin-web".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "vaultwarden".into(),
            name: "Vaultwarden".into(),
            tagline: "Lightweight Bitwarden server written in Rust".into(),
            description: "Vaultwarden is an alternative implementation of the Bitwarden server API written in Rust, ideal for self-hosting on low-power devices.".into(),
            category: "self-hosted".into(),
            homepage: "https://github.com/dani-garcia/vaultwarden".into(),
            license: "AGPL-3.0".into(),
            tags: vec!["passwords".into(), "security".into(), "rust".into(), "server".into()],
            featured: true,
            install: vec![
                InstallOption { method: "aur".into(), command: "paru -S vaultwarden".into(), notes: None },
            ],
        },

        // ==================== EDUCATION ====================
        SoftwareEntry {
            id: "anki".into(),
            name: "Anki".into(),
            tagline: "Powerful, intelligent spaced repetition flashcards".into(),
            description: "Anki is a program which makes remembering things easy using spaced repetition, far more effective than traditional study methods.".into(),
            category: "education".into(),
            homepage: "https://apps.ankiweb.net/".into(),
            license: "AGPL-3.0".into(),
            tags: vec!["flashcards".into(), "learning".into(), "memory".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S anki".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub net.ankiweb.Anki".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "calibre".into(),
            name: "Calibre".into(),
            tagline: "Comprehensive e-book manager and reader".into(),
            description: "Calibre is the one stop solution to all your e-book needs. Organize books into libraries, convert between e-reader formats, and sync to devices.".into(),
            category: "education".into(),
            homepage: "https://calibre-ebook.com/".into(),
            license: "GPL-3.0".into(),
            tags: vec!["ebook".into(), "reader".into(), "library".into()],
            featured: true,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S calibre".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub com.calibre_ebook.calibre".into(), notes: None },
            ],
        },
        SoftwareEntry {
            id: "stellarium".into(),
            name: "Stellarium".into(),
            tagline: "Free open-source 3D planetarium for your computer".into(),
            description: "Stellarium shows a realistic sky in 3D, just like what you see with the naked eye, binoculars, or a telescope.".into(),
            category: "education".into(),
            homepage: "https://stellarium.org/".into(),
            license: "GPL-2.0".into(),
            tags: vec!["astronomy".into(), "space".into(), "science".into()],
            featured: false,
            install: vec![
                InstallOption { method: "pacman".into(), command: "sudo pacman -S stellarium".into(), notes: None },
                InstallOption { method: "flatpak".into(), command: "flatpak install flathub org.stellarium.Stellarium".into(), notes: None },
            ],
        },
    ]
}

